spring.datasource.url=${monolib.data.url}
spring.datasource.username=${monolib.data.user}
spring.datasource.password=${monolib.data.password}
spring.datasource.driver-class-name=${monolib.data.driver}

spring.flyway.enabled=true
