name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.ref_name == 'master' || startsWith(github.ref_name, 'hotfix/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Calculate semantic version
        id: semver
        uses: PaulHatch/semantic-version@v6.0.1
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE|!:"
          minor_pattern: "^feat"
          version_format: "${major}.${minor}.${patch}"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Update revision property
        run: |
          mvn -B versions:set-property \
            -Dproperty=revision \
            -Drevision=${{ steps.semver.outputs.version }} \
            -DnewVersion=${{ steps.semver.outputs.version }} \
            -DgenerateBackupPoms=false

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add pom.xml
          
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 1;
          else
            git commit -m "chore: bump version to ${{ steps.semver.outputs.version }}"
            git push origin ${{ github.ref_name }} 
          fi

      - name: Create and push tag
        run: |
          git tag ${{ steps.semver.outputs.version_tag }}
          git push origin ${{ steps.semver.outputs.version_tag }}

      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.semver.outputs.version_tag }}
          fetch-depth: 0

      - name: Deploy
        run: mvn clean deploy -Drevision=${{ steps.semver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.semver.outputs.version_tag }}
          generate_release_notes: true
